# Setup
title: Process work for IxD Courses
url: https://ixdwtruong.github.io
paginate: 4
baseurl: ""
permalink: pretty

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: Wilson Truong
  url: 
  email: truonwil@sheridancollege.ca

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about
